elasticsearch:
    image: "elasticsearch:1.5"
    volumes:
        - "./data/elasticsearch:/data"
    ports:
        - "9200:9200"
        - "9300:9300"

php:
    build: "./docker/php"
    links:
        - "db_website:db_website"
        - "db_cache_back:db_cache_back"
        - "elasticsearch:search_engine"
    ports:
        - "9000:9000"
    volumes:
        - "./website:/srv/http/website"
        - "./blog:/srv/http/blog"
        - "./work:/srv/http/work"
        - "./connect:/srv/http/connect"
        - "./cache/back:/srv/http/cache_back"

www:
    image: "jwilder/nginx-proxy:latest"
    volumes:
        - "/var/run/docker.sock:/tmp/docker.sock"
        - "./log/www:/var/log/nginx"
    ports:
        - "80:80"

db_website:
    image: "orchardup/postgresql:9.3"
    ports:
        - "5432:5432"
    environment:
        POSTGRESQL_USER: "didierio"
        POSTGRESQL_PASS: "didierio"
        POSTGRESQL_DB: "didierio"
    volumes:
        - "./data/postgresql:/var/lib/postgresql"

http_website:
    image: "nginx:latest"
    links:
        - "php:webstack_php"
    volumes:
        - "./website:/var/www"
        - "./docker/website/nginx.conf:/nginx.conf"
        - "./log/website:/var/log/nginx"
    ports:
        - "9001:9001"
    command: "nginx -c /nginx.conf"
    environment:
        VIRTUAL_HOST: "www.dev.didier.io"
        VIRTUAL_PORT: "9001"

http_connect:
    image: "nginx:latest"
    links:
        - "php:webstack_php"
        - "db_website:db_website"
    volumes:
        - "./connect:/var/www"
        - "./docker/connect/nginx.conf:/nginx.conf"
        - "./log/connect:/var/log/nginx"
    ports:
        - "9002:9002"
    command: "nginx -c /nginx.conf"
    environment:
        VIRTUAL_HOST: 'connect.dev.didier.io'
        VIRTUAL_PORT: "9002"

db_cache_back:
    build: "./docker/db_cache_back"
    ports:
        - "10001:10001"
    environment:
        POSTGRESQL_USER: "didierio_cache"
        POSTGRESQL_PASS: "didierio_cache"
        POSTGRESQL_DB: "didierio_cache"
    volumes:
        - "./data/postgresql:/var/lib/postgresql"

http_cache_back:
    image: "nginx:latest"
    links:
        - "php:webstack_php"
        - "db_cache_back:db_cache_back"
    volumes:
        - "./cache/back:/var/www"
        - "./docker/cache_back/nginx.conf:/nginx.conf"
        - "./log/cache_back:/var/log/nginx"
    ports:
        - "9003:9003"
    command: "nginx -c /nginx.conf"
    environment:
        VIRTUAL_HOST: "cache.dev.didier.io"
        VIRTUAL_PORT: "9003"
